# Generated by Django 5.1 on 2024-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField()),
                ('density', models.FloatField(null=True)),
                ('avg_neighbor_rating', models.FloatField(null=True)),
                ('predicted_score', models.FloatField(null=True)),
            ],
        ),
    ]
